name: interfaces_fedorov_coursework_nao
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  http: ^0.13.0
  form_inputs:
    path: packages/form_inputs
  image_picker: ^0.8.8
  url_launcher: ^6.1.11
  http_parser: ^4.0.2
  auto_route: ^7.4.0
  flutter_svg: ^2.0.7
  network_to_file_image: ^4.0.1
  path_provider: ^2.0.15
  dio: ^4.0.6
  easy_sidemenu: ^0.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
