// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbvgbStPEXZOApsVJ0fW6uUdMwUTHk2i4',
    appId: '1:170198156444:web:55dfef8bda215e69acd959',
    messagingSenderId: '170198156444',
    projectId: 'sauce-nao-ver0',
    authDomain: 'sauce-nao-ver0.firebaseapp.com',
    storageBucket: 'sauce-nao-ver0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NksP0_LkRazTPoPDdyTieNk8gVKb_iE',
    appId: '1:170198156444:android:2da1fda2c331d603acd959',
    messagingSenderId: '170198156444',
    projectId: 'sauce-nao-ver0',
    storageBucket: 'sauce-nao-ver0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4HMjsnD7cdUp6bGhz9V56gYbltqmUHXQ',
    appId: '1:170198156444:ios:46be89ef6d9a27d6acd959',
    messagingSenderId: '170198156444',
    projectId: 'sauce-nao-ver0',
    storageBucket: 'sauce-nao-ver0.appspot.com',
    iosClientId:
        '170198156444-htoor15o3a6ers7e9c9ubhinfcrjge5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.interfacesFedorovCourseworkNao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4HMjsnD7cdUp6bGhz9V56gYbltqmUHXQ',
    appId: '1:170198156444:ios:46be89ef6d9a27d6acd959',
    messagingSenderId: '170198156444',
    projectId: 'sauce-nao-ver0',
    storageBucket: 'sauce-nao-ver0.appspot.com',
    iosClientId:
        '170198156444-htoor15o3a6ers7e9c9ubhinfcrjge5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.interfacesFedorovCourseworkNao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbvgbStPEXZOApsVJ0fW6uUdMwUTHk2i4',
    appId: '1:170198156444:web:ccd6dce77bba2bc7acd959',
    messagingSenderId: '170198156444',
    projectId: 'sauce-nao-ver0',
    authDomain: 'sauce-nao-ver0.firebaseapp.com',
    storageBucket: 'sauce-nao-ver0.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCbvgbStPEXZOApsVJ0fW6uUdMwUTHk2i4',
    appId: '1:170198156444:web:5774572656b0f8b5acd959',
    messagingSenderId: '170198156444',
    projectId: 'sauce-nao-ver0',
    authDomain: 'sauce-nao-ver0.firebaseapp.com',
    storageBucket: 'sauce-nao-ver0.appspot.com',
  );
}
